# A quick hack for running the pipeline on samples from the draft paper
# (Nasir et al, "A comparison of whole genome sequencing of Sars-CoV-2...")
#
# Currently we have a wrapper script 'c19_make_pipeline.py' to create a
# pipeline directory, but it was written with pipeline testing in mind, and
# needs a little refactoring before it will be convenient for real data. 
#
# In the meantime you can use the following hack.
#
#  1. Create a dummy pipeline run 'Paper1':
#
#      ./c19_make_pipeline.py -o Paper1 $HOME/data/MT-swab-Iran-Liverpool*.fastq.gz
#
#  2. Overwrite the config file with the contents of this file:
#
#      cp -f paper1_config.yaml Paper1/config.yaml
#
#  3. Edit Paper1/config.yaml to replace /home/kmsmith/data with the pathname
#     to your data directory.
#
#  4. Run the pipeline:
#
#      cd Paper1
#      snakemake -kp --cores=16 --use-conda --conda-prefix=$HOME/.snakemake all    


# This file contains a high-level summary of pipeline configuration and inputs.
# It is ingested by the Snakefile, and also intended to be human-readable.

# Used as -a,-A arguments to 'cutadapt'
primer_rc: '/home/kmsmith/data/wuhan_primers_28.01.20_trim_RC.fa'
primer_fw: '/home/kmsmith/data/wuhan_primers_28.01.20_trim_FW.fa'

# Last arguments on 'trimmomatic' command line (after input, output files)
trimmomatic_args: 'ILLUMINACLIP:/home/kmsmith/data/NexteraPE-PE.fa:2:30:10 SLIDINGWINDOW:4:20'

# Used as hisat2 reference genome when removing host sequences.
# Also used as 'ivar' reference genome in variant detection + consensus.
hostremove_reference: '/home/kmsmith/data/MN908947_3.fasta'

# Used as --reference argument to 'breseq'
breseq_reference: '/home/kmsmith/data/MN908947_primer_annotated_prot_clinical.gb'

# Used as --db argument to 'kraken2'
kraken2_db: '/home/kmsmith/data/Kraken2/db'

# Consensus and variant calling ivar/samtools params from https://github.com/connor-lab/ncov2019-artic-nf/blob/master/conf/illumina.config
mpileup_depth: 100000
# ivar frequency threshold to build consensus
ivar_freq_threshold: 0.75
# Minimum coverage depth to call variant
ivar_min_coverage_depth: 10
# iVar frequency threshold to call variant (ivar variants: -t )
ivar_min_freq_threshold: 0.25
# iVar minimum mapQ to call variant (ivar variants: -q)
ivar_min_variant_quality: 20

# lmat_fragment_size: size of fragments (in bp) analyzed by 'lmat'
# Absolute pathname of the LMAT DB is {lmat_basedir}/data/{lmat_db}.
# LMAT's expected "runtime inputs" (e.g. 'ncbi_taxid_to_rank.txt') should be in {lmat_basedir}/runtime_inputs.
lmat_fragment_size: 250
lmat_basedir: '/home/kmsmith/data/LMAT-1.2.6'
lmat_db: 'kML+Human.v4-14.20.g10.db'

# Used as -r,-g arguments to 'quast'
quast_reference_genome: '/home/kmsmith/data/MN908947_3.fasta'
quast_feature_coords: '/home/kmsmith/data/MN908947_3.gff3'

# List of samples to be analyzed follows.
# Dictionary is keyed by sample name (=directory name).
# Input filenames are relative to sample directory (or absolute).

samples:
  ARTIC-NEG:
    input_fastq_files_R1:
    - /home/kmsmith/data/sars-cov-2/ARTIC/NEG_S15_L001_R1_001.fastq.gz
    input_fastq_files_R2:
    - /home/kmsmith/data/sars-cov-2/ARTIC/NEG_S15_L001_R2_001.fastq.gz
  Iran1-ARTIC:
    input_fastq_files_R1:
    - /home/kmsmith/data/sars-cov-2/ARTIC/Iran-MT_S2_L001_R1_001.fastq.gz
    input_fastq_files_R2:
    - /home/kmsmith/data/sars-cov-2/ARTIC/Iran-MT_S2_L001_R2_001.fastq.gz
  Iran1-LA:
    input_fastq_files_R1:
    - /home/kmsmith/data/sars-cov-2/round2/human/MT-swab-Iran-Liverpool-pool1-baited_S15_L001_R1_001.fastq.gz
    - /home/kmsmith/data/sars-cov-2/round2/human/MT-swab-Iran-Liverpool-pool2-baited_S19_L001_R1_001.fastq.gz
    input_fastq_files_R2:
    - /home/kmsmith/data/sars-cov-2/round2/human/MT-swab-Iran-Liverpool-pool1-baited_S15_L001_R2_001.fastq.gz
    - /home/kmsmith/data/sars-cov-2/round2/human/MT-swab-Iran-Liverpool-pool2-baited_S19_L001_R2_001.fastq.gz
  Iran1-LN:
    input_fastq_files_R1:
    - /home/kmsmith/data/sars-cov-2/round2/human/MT-swab-Iran-Liverpool-pool1_S3_L001_R1_001.fastq.gz
    - /home/kmsmith/data/sars-cov-2/round2/human/MT-swab-Iran-Liverpool-pool2_S7_L001_R1_001.fastq.gz
    input_fastq_files_R2:
    - /home/kmsmith/data/sars-cov-2/round2/human/MT-swab-Iran-Liverpool-pool1_S3_L001_R2_001.fastq.gz
    - /home/kmsmith/data/sars-cov-2/round2/human/MT-swab-Iran-Liverpool-pool2_S7_L001_R2_001.fastq.gz
  Iran1-RA:
    input_fastq_files_R1:
    - /home/kmsmith/data/sars-cov-2/round2/human/MT-swab-Iran-RandomHex-baited_S23_L001_R1_001.fastq.gz
    input_fastq_files_R2:
    - /home/kmsmith/data/sars-cov-2/round2/human/MT-swab-Iran-RandomHex-baited_S23_L001_R2_001.fastq.gz
  Iran1-RN:
    input_fastq_files_R1:
    - /home/kmsmith/data/sars-cov-2/round2/human/MT-swab-Iran-RandomHex_S11_L001_R1_001.fastq.gz
    input_fastq_files_R2:
    - /home/kmsmith/data/sars-cov-2/round2/human/MT-swab-Iran-RandomHex_S11_L001_R2_001.fastq.gz
  Wuhan1-ARTIC:
    input_fastq_files_R1:
    - /home/kmsmith/data/sars-cov-2/ARTIC/Wuhan-NP_S1_L001_R1_001.fastq.gz
    input_fastq_files_R2:
    - /home/kmsmith/data/sars-cov-2/ARTIC/Wuhan-NP_S1_L001_R2_001.fastq.gz
  Wuhan1-LA:
    input_fastq_files_R1:
    - /home/kmsmith/data/sars-cov-2/round2/human/JAN29-NP-swab-Wuhan-Liverpool-pool1-bait_S16_L001_R1_001.fastq.gz
    - /home/kmsmith/data/sars-cov-2/round2/human/JAN29-NP-swab-Wuhan-Liverpool-pool2-bait_S20_L001_R1_001.fastq.gz
    input_fastq_files_R2:
    - /home/kmsmith/data/sars-cov-2/round2/human/JAN29-NP-swab-Wuhan-Liverpool-pool1-bait_S16_L001_R2_001.fastq.gz
    - /home/kmsmith/data/sars-cov-2/round2/human/JAN29-NP-swab-Wuhan-Liverpool-pool2-bait_S20_L001_R2_001.fastq.gz
  Wuhan1-LN:
    input_fastq_files_R1:
    - /home/kmsmith/data/sars-cov-2/round2/human/JAN29-NP-swab-Wuhan-Liverpool-pool1_S4_L001_R1_001.fastq.gz
    - /home/kmsmith/data/sars-cov-2/round2/human/JAN29-NP-swab-Wuhan-Liverpool-pool2_S8_L001_R1_001.fastq.gz
    input_fastq_files_R2:
    - /home/kmsmith/data/sars-cov-2/round2/human/JAN29-NP-swab-Wuhan-Liverpool-pool1_S4_L001_R2_001.fastq.gz
    - /home/kmsmith/data/sars-cov-2/round2/human/JAN29-NP-swab-Wuhan-Liverpool-pool2_S8_L001_R2_001.fastq.gz
  Wuhan1-RA:
    input_fastq_files_R1:
    - /home/kmsmith/data/sars-cov-2/round2/human/JAN29-NP-swab-Wuhan-RandomHex-baited_S24_L001_R1_001.fastq.gz
    input_fastq_files_R2:
    - /home/kmsmith/data/sars-cov-2/round2/human/JAN29-NP-swab-Wuhan-RandomHex-baited_S24_L001_R2_001.fastq.gz
  Wuhan1-RN:
    input_fastq_files_R1:
    - /home/kmsmith/data/sars-cov-2/round2/human/JAN29-NP-swab-Wuhan-RandomHex_S12_L001_R1_001.fastq.gz
    input_fastq_files_R2:
    - /home/kmsmith/data/sars-cov-2/round2/human/JAN29-NP-swab-Wuhan-RandomHex_S12_L001_R2_001.fastq.gz
